app = "giraffeclaude-phkl2a"
primary_region = "fra"

[build]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/status"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
